tournament:
    path:     /
    defaults: { _controller: "FdaTournamentBundle:Tournament:index" }

tournament_show:
    path:     /{id}/show
    defaults: { _controller: "FdaTournamentBundle:Tournament:show" }

tournament_details:
    path:     /{tournamentId}/details
    defaults: { _controller: "FdaTournamentBundle:Tournament:details" }

tournament_new:
    path:     /new
    defaults: { _controller: "FdaTournamentBundle:Tournament:new" }

tournament_edit:
    path:     /{id}/edit
    defaults: { _controller: "FdaTournamentBundle:Tournament:edit" }

tournament_update:
    path:     /{id}/update
    defaults: { _controller: "FdaTournamentBundle:Tournament:update" }
    methods:  [POST, PUT]

tournament_delete:
    path:     /{id}/delete
    defaults: { _controller: "FdaTournamentBundle:Tournament:delete" }
    methods:  [POST, DELETE]

game_show:
    path:     /game/{gameId}/show
    defaults: { _controller: "FdaTournamentBundle:Game:show" }