services:
  fda.tournament.manager:
    class: Fda\TournamentBundle\Manager\TournamentManager
    calls:
      - [setEntityManager,[@doctrine.orm.default_entity_manager]]

  fda.tournament.engine:
    class: Fda\TournamentBundle\Engine\TournamentEngine
    calls:
      - [setEntityManager,[@doctrine.orm.default_entity_manager]]
#      - [setRoundGearsFactory,[@fda.tournament.round_gears_factory]]
      - [setEngineFactory,[@fda.tournament.engine_factory]]
      - [setLogger,[@logger]]

  fda.tournament.engine_factory:
    class: Fda\TournamentBundle\Engine\Factory\TournamentEngineFactory
    calls:
      - [setEntityManager,[@doctrine.orm.default_entity_manager]]
      - [setRoundGearsFactory,[@fda.tournament.round_gears_factory]]
#    public: false

  fda.tournament.round_gears_factory:
    class: Fda\TournamentBundle\Engine\Factory\RoundGearsFactory
    calls:
      - [setEntityManager,[@doctrine.orm.default_entity_manager]]
      - [setGameGearsFactory,[@fda.tournament.game_gears_factory]]
      - [setEventDispatcher,[@event_dispatcher]]
      - [setLogger,[@logger]]
    public: false

  fda.tournament.game_gears_factory:
    class: Fda\TournamentBundle\Engine\Factory\GameGearsFactory
    calls:
      - [setEntityManager,[@doctrine.orm.default_entity_manager]]
      - [setLegGearsFactory,[@fda.tournament.leg_gears_factory]]
      - [setEventDispatcher,[@event_dispatcher]]
      - [setLogger,[@logger]]
    public: false

  fda.tournament.leg_gears_factory:
    class: Fda\TournamentBundle\Engine\Factory\LegGearsFactory
    calls:
      - [setEntityManager,[@doctrine.orm.default_entity_manager]]
      - [setEventDispatcher,[@event_dispatcher]]
      - [setLogger,[@logger]]
    public: false

#  fda.tournament.gears.all_vs_all:
#    class: Fda\TournamentBundle\Engine\TournamentGearsAllVsAll
#    lazy: true
#    calls:
#      - [setEngine,[@fda.tournament.engine]]
#      - [setEntityManager,[@doctrine.orm.default_entity_manager]]
#
#  fda.game.gears.simple:
#    class: Fda\TournamentBundle\Engine\SimpleGameGears
#    lazy: true
#    calls:
#      - [setEngine,[@fda.tournament.engine]]
#      - [setEntityManager,[@doctrine.orm.default_entity_manager]]
#
#  fda.leg.gears.simple:
#    class: Fda\TournamentBundle\Engine\SimpleLegGears
#    lazy: true
#    calls:
#      - [setEngine,[@fda.tournament.engine]]
#      - [setEntityManager,[@doctrine.orm.default_entity_manager]]

  fda.tournament.twig.extension:
    class: Fda\TournamentBundle\Twig\TournamentExtension
    calls:
      - [setTournamentEngine,[@fda.tournament.engine]]
      - [setTournamentManager,[@fda.tournament.manager]]
    tags:
      - { name: twig.extension }

  fda.tournament.new_tournament_wizard:
    class: Fda\TournamentBundle\Form\TournamentWizard
    parent: craue.form.flow
    scope: request
    calls:
      - [setPlayerManager,[@fda.player.manager]]

  fda.tournament.engine_logger:
    class: Fda\TournamentBundle\Engine\EngineLogger
    calls:
      - [setLogger,[@logger]]
    tags:
      - { name: kernel.event_subscriber }
