security:
  providers:
    choice:
      id: choice_auth.user_provider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login_firewall:
      pattern:   ^/login$
      anonymous: ~

    main:
      pattern: ^/
      choice_auth: ~
      logout:
        path:   /logout

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: ROLE_USER }