fda_dsb_homepage:
  path:     /
  defaults: { _controller: FdaDsbBundle:Default:index }

FdaPlayerBundle_player:
  resource: "@FdaPlayerBundle/Resources/config/routing.yml"
  prefix:   /player

FdaBoardBundle_board:
  resource: "@FdaBoardBundle/Resources/config/routing.yml"
  prefix:   /board