fda_dsb_homepage:
  path:     /
  defaults: { _controller: FdaDsbBundle:Default:index }

BigScreen_index:
  path:     /big-screen
  defaults: { _controller: FdaDsbBundle:BigScreen:index }
BigScreen_async_board_info:
  path:     /big-screen/board/{boardId}
  defaults: { _controller: FdaDsbBundle:BigScreen:fetchBoardInfo }

FdaPlayerBundle_player:
  resource: "@FdaPlayerBundle/Resources/config/routing.yml"
  prefix:   /player

FdaBoardBundle_board:
  resource: "@FdaBoardBundle/Resources/config/routing.yml"
  prefix:   /board

FdaTournamentBundle_tournament:
  resource: "@FdaTournamentBundle/Resources/config/routing.yml"
  prefix:   /tournament

FdaRefereeBundle:
  resource: "@FdaRefereeBundle/Resources/config/routing.yml"
  prefix:   /referee
