services:
  fda.ledger:
    class: Fda\RefereeBundle\Ledger\Ledger
    calls:
      - [setSession,[@session]]
      - [setPlayerManager,[@fda.player.manager]]
      - [setBoardManager,[@fda.board.manager]]
      - [setTournamentEngine,[@fda.tournament.engine]]
      - [setEventDispatcher,[@event_dispatcher]]

  fda.referee.twig.extension:
    class: Fda\RefereeBundle\Twig\RefereeExtension
    calls:
      - [setLedger,[@fda.ledger]]
    tags:
      - { name: twig.extension }