services:
  fda.player.manager:
    class: Fda\PlayerBundle\Manager\PlayerManager
    calls:
      - [setEntityManager,[@doctrine.orm.default_entity_manager]]

  fda.player.form.type.player_choice:
    class: Fda\PlayerBundle\Form\Type\PlayerChoice
    tags:
      - { name: form.type, alias: player_choice }

  fda.player.twig.extension:
    class: Fda\PlayerBundle\Twig\PlayerExtension
    calls:
      - [setPlayerManager,[@fda.player.manager]]
    tags:
      - { name: twig.extension }
